### PR TITLE
Revised header styling (WIP)

### PR DESCRIPTION
**Pull request by TalD**
Revised header styling (WIP)

### CODE REVIEW

**Comment by MichaelRFairhurst** [comment]
This looks super awesome!!!!! This is sweet!

I actually have a different repo for docs now, but I merged your stuff in just fine and I'm going to deploy it tonight!

**Comment by TalD** [comment]
Revised sidebar as well (WIP). What branch should I fork for the docs?

**Comment by MichaelRFairhurst** [comment]
I made a repo for it here: https://github.com/MichaelRFairhurst/wake-compiler-docs, now we can just use master

There's some whitespace around the blue at the top, was the banner supposed to fill from side to side? Also, you should try to make it out to coders night tonight!

**Comment by MichaelRFairhurst** [comment]
I'm gonna close this - I merged it into the docs repo and deployed it yesterday!

**Pull request closed without merging**
